import { test, expect } from '@playwright/test'
import {
  registerAndLogin,
  createBoard,
  createColumn,
  createTaskViaUI,
  main,
} from './helpers'

test.describe('Activity panel', () => {
  test('activity button opens the activity panel', async ({ page }) => {
    await registerAndLogin(page, 'activity-open')
    await createBoard(page, 'Activity Board')

    await main(page).getByRole('button', { name: 'Activity' }).click()

    // The activity panel has a "No activity yet" empty state or filter dropdowns
    await expect(page.getByText('No activity yet')).toBeVisible()
  })

  test('activity panel renders with filter controls', async ({ page }) => {
    await registerAndLogin(page, 'activity-create')
    await createBoard(page, 'Activity Board')

    // Open activity panel
    await main(page).getByRole('button', { name: 'Activity' }).click()

    // Verify the panel opens with its filter UI (activity data is not auto-generated by the API)
    const dialog = page.getByRole('dialog')
    await expect(dialog).toBeVisible()
    await expect(dialog.getByText(/activity/i).first()).toBeVisible()
  })
})
